---
swagger: "2.0"
info:
  description: "AI Photo Search application, built during the Cloud and Big Data course\
    \ at Columbia University."
  version: "1.0.0"
  title: "AI Photo Search"
host: "y2vv1vh0m3.execute-api.us-east-1.amazonaws.com"
basePath: "/Dev"
schemes:
  - "https"
paths:
  /search:
    get:
      summary: photo search method
      description: |
        This API takes in a search query as a query parameter and returns zero or more photos that match the search query.
      operationId: "searchPhotos"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "q"
          in: "query"
          required: true
          type: "string"
      responses:
        "200":
          description: "search results"
          schema:
            $ref: "#/definitions/SearchResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/Error"
  /upload/{bucket}/{key}:
    put:
      summary: photo upload method
      description: |
        This API takes in the multi-part body sent to it (ex. a photo) and uploads it to an S3 bucket.
      consumes:
        - "image/jpeg"
        - "image/png"
        - "image/jpg"
      produces:
        - "application/json"
      parameters:
        - name: "key"
          in: "path"
          required: true
          type: "string"
          description: "The filename of the photo being uploaded"
        - name: "bucket"
          in: "path"
          required: true
          type: "string"
          description: "The name of the S3 bucket to upload to"
        - name: "x-amz-meta-customLabels"
          in: "header"
          required: false
          type: "string"
          description: "The custom labels to be associated with the photo"
      responses:
        "200":
          description: "S3 PUT operation response"
          schema:
            type: "object"
        "500":
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  Photo:
    type: "object"
    properties:
      url:
        type: "string"
      labels:
        type: "array"
        items:
          type: "string"
  SearchResponse:
    type: "object"
    properties:
      results:
        type: "array"
        items:
          $ref: "#/definitions/Photo"
